### ISSUE TITLE
Increase draw range at least up to image tracking range

### ISSUE THREAD

**Issue by CapSparkle** [artoolkitx/jsartoolkit5#103]
I realized that range of stable image tracking is much more bigger than drawing range! 

You can see that on the **first** screenshot there is debug notifications about stable image tracking but there is no any 3d content.
And on the **second** when i get my marker really close - it appears. 

Is that any way to increase drawing range? I have tested flamingo example - it works the same way. I draws only really close range.
I have tried to increase scale (**third** screenshot)- i didn't succeed it that way

![Скриншот 01-12-2020 160036](https://user-images.githubusercontent.com/25351821/100720593-d2fe9780-33f0-11eb-9e0f-3abfa9536086.png)

![Скриншот 01-12-2020 160204](https://user-images.githubusercontent.com/25351821/100720612-db56d280-33f0-11eb-9ccd-af8266190b0a.png)

![Скриншот 01-12-2020 160924](https://user-images.githubusercontent.com/25351821/100720627-deea5980-33f0-11eb-9ae1-d6df3220e0d9.png)

**Comment by NewYearCelebrate** [comment]
I have found a solution of that issue! It is because of setup projectionMatrix of camera. That matrix clips rendering scene. And second - you have yo use Perspective camera instead of Camera. There is note about not using directry Camera class in three.js docs
![image](https://user-images.githubusercontent.com/76193663/103149940-2a4e1880-47a1-11eb-83ed-237bfc9bb4e9.png)

**Comment by NewYearCelebrate** [comment]
That issue should be closed

**Comment by kalwalt** [comment]
I also think that should be better to use the Perspective Camera, not sure about the ste CameraMatrix, Anyway thanks for this!
